### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by johnhkchen** [joshua-mo-143/shuttle-axum-htmx-ex#1]
Hello,

Thanks for putting out this project, and I had a great deal of interest in trying it out, but I found it challenging to get off the ground. Do you think it'd be possible to include a README so we can clone the project and get going? I tried following along the blog post, but couldn't really without first getting the repo cloned, but now I'm unable to build or deploy it as it crashes for me.

**Comment by joshua-mo-143** [comment]
Hey! I've been meaning to keep this repo updated but have forgotten. Will update now.

**Comment by joshua-mo-143** [comment]
Hi again, please feel free to try building/deploying again - I have added some install instructions as well as updated the dependencies.

As a sidenote for anyone else who is having trouble with this: try updating the Shuttle-related dependencies to the current version (v0.32.0 at the current time of writing) and make sure your cargo-shuttle version is also at v0.32.0 - if you're experiencing any other issues past this, please feel free to let me know and I'll try to help you debug it.

**Comment by johnhkchen** [comment]
<img width="473" alt="Screenshot 2023-11-14 at 8 34 08 PM" src="https://github.com/joshua-mo-143/shuttle-axum-htmx-ex/assets/14898949/6a9e3a50-d490-4883-bd2b-fc53a1c6b75e">

Very helpful, thank you so much!
