### ISSUE TITLE
Can not work on windows

### ISSUE THREAD

**Issue by qqke** [joshua-mo-143/shuttle-axum-htmx-ex#2]
`
thread 'main' panicked at C:\Users\circleci\project\cargo-shuttle\src\lib.rs:1563:51:
called `Result::unwrap()` on an `Err` value: Failed to verify the version of shuttle-runtime in C:\work\sba\target\debug\sba.exe. Is cargo targeting the correct executable?

Caused by:
    0: Checking the version of shuttle-runtime timed out. Make sure the executable is using #[shuttle-runtime::main].
    1: deadline has elapsed

Stack backtrace:
   0: git_odb_object_data
   1: git_odb_object_data
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: git_odb_object_data
  10: <unknown>
  11: git_credential_userpass_plaintext_new
  12: BaseThreadInitThunk
  13: RtlUserThreadStart
stack backtrace:
   0:     0x7ff7cbaee252 - git_odb_object_data
   1:     0x7ff7cbb1704d - git_odb_object_data
   2:     0x7ff7cbae7921 - git_odb_object_data
   3:     0x7ff7cbaee07a - git_odb_object_data
   4:     0x7ff7cbaf0ef9 - git_odb_object_data
   5:     0x7ff7cbaf0bb5 - git_odb_object_data
   6:     0x7ff7cbaf1414 - git_odb_object_data
   7:     0x7ff7cbaf12e9 - git_odb_object_data
`

**Comment by joshua-mo-143** [comment]
Hey there! Thanks for opening the issue.

What version of `cargo-shuttle` are you using and have you updated your Shuttle-related dependencies?

**Comment by qqke** [comment]
Maybe it is wrong with
My docker  i fixed it now
